apiVersion: v1
kind: Service
metadata:
  name: demo-workshop-service
  namespace: demo-workshop
spec:
  selector:
    app: demo-workshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
